### ISSUE TITLE
Provide Salt renderer

### ISSUE THREAD

**Issue by lechat** [lhupfeldt/multiconf#21]
Hi,

I think that Multiconf could be used as state holder for Salt (http://saltstack.org), but what is required is a Salt renderer, which will translate Multiconf to structure understood by Salt (http://docs.saltstack.com/topics/tutorials/starting_states.html#understanding-the-render-system)

Any thoughts?

Aleksey

**Comment by lhupfeldt** [comment]
Aleksey, feel free to reopen if you are still interrested.
