### ISSUE TITLE
Allow @required decorator to take a list

### ISSUE THREAD

**Issue by andywis** [lhupfeldt/multiconf#26]
As a programmer using multiconfi, I would like to supply the parameters to the @required decorator as a list, not as a string with commas in.
This would be help readability when there are many @required parameters. It would also be nice to have it on other decorators, e.g. @nested_repeatables.

Thanks
Andy Watkins

**Comment by lhupfeldt** [comment]
Hi Andy,

I will make it support both syntaxes, when I get some spare time.

Regards
LArs

**Comment by lhupfeldt** [comment]
<code>@required</code>, <code>@required_if</code> and <code>@nested_repeatable</code> now supports <code>*args</code> in addition to the existing syntax
