### ISSUE TITLE
pip install multiconf not working

### ISSUE THREAD

**Issue by henriklynggaard** [lhupfeldt/multiconf#27]
Downloading/unpacking multiconf

  Getting page https://pypi.python.org/simple/multiconf/
  Could not fetch URL https://pypi.python.org/simple/multiconf/: HTTP Error 404: Not Found
  Will skip URL https://pypi.python.org/simple/multiconf/ when looking for download links for multiconf
  Getting page https://pypi.python.org/simple/
  URLs to search for versions for multiconf:
  * https://pypi.python.org/simple/multiconf/
  Getting page https://pypi.python.org/simple/multiconf/
  Could not fetch URL https://pypi.python.org/simple/multiconf/: HTTP Error 404: Not Found
  Will skip URL https://pypi.python.org/simple/multiconf/ when looking for download links for multiconf
  Could not find any downloads that satisfy the requirement multiconf

**Comment by lhupfeldt** [comment]
Hi Henrik

multiconf is pip installable, but not from pypi. I will get it there eventually, when I have automated the versioning and got the test suite back to 100% coverage. But be aware that it will be the newest version, not the one you are using.

**Comment by lhupfeldt** [comment]
Now has setup.py, but still not on pypi

**Comment by lechat** [comment]
Fails one test: https://travis-ci.org/lechat/multiconf/builds/51069555

Lars, please setup it on Travis-CI, it takes three minutes to do so!

**Comment by lhupfeldt** [comment]
Hi Aleksey. Now it is on travis.
I increased the verbosity, because I could not see why your build failed, and changed the travis setup to use 'setup.py test'. But I could not reproduce the error.
Are you using multiconf?

**Comment by lhupfeldt** [comment]
Should stay one until on pypi.

**Comment by lhupfeldt** [comment]
Is now on pypi
