### ISSUE TITLE
On missing key error, do not dump child objects

### ISSUE THREAD

**Issue by madsflensted** [lhupfeldt/multiconf#28]
When working with large configurations, the error dump  is so long that it makes it hard to find the actual problem.

I think it would be sufficient if the error dump only displayed the object attributes at the level the error occurred (i.e. did not dump child objects).

**Comment by lhupfeldt** [comment]
I agree. I will try to find time to implement this.

**Comment by lhupfeldt** [comment]
Finally implemented in 6.0.0.
