### ISSUE TITLE
Add multiconf attirbutes to __dir__()

### ISSUE THREAD

**Issue by madsflensted** [lhupfeldt/multiconf#29]
When working with large configurations, it would be helpfull to be able to explore the loaded config via tools like ipython. The ipython shell does tab completion of attributes and object methods, based on what is returned by `dir()`. By adding multiconf attributes and property methods to output of `dir()` it would greatly help when using such tools.

**Comment by lhupfeldt** [comment]
I agree, dir() should list multiconf attributes. I think it is a minor bug as it does not affect the functionality of multiconf, but I will try to find time to fix it.

**Comment by lhupfeldt** [comment]
Implemented in 6.1.0 for Python 3 only. I will not implement for Python 2, it seem impossible to make a sensible implementation.
