### ISSUE TITLE
Options to dumping of configuration

### ISSUE THREAD

**Issue by madsflensted** [lhupfeldt/multiconf#30]
When working with large configurations it is sometimes neceseary to search for a value, and the finding the corresponding places in the model where it is created.

To fascilitate simple `grep`'ing, it would be great if dump object had an option to print fully qualified keys.

E.g. conceptually:

```
'project.name': 'foo',
'project.server.name': 'bar-server'
'project.server.port': '8888'
``
```

**Comment by lhupfeldt** [comment]
I would prefer to not implement this in multiconf if there is an external tool which can transform the json dump in this way. If not, then I will implement it whn I get the time.

**Comment by lhupfeldt** [comment]
https://github.com/tomnomnom/gron does this transformation, so closing this.
