### ISSUE TITLE
Remove circle.yml?

### ISSUE THREAD

**Issue by keilw** [lhupfeldt/multiconf#31]
Hi,
It seems the circle.yml configuration was not used for some time. CircleCI will switch off version 1, so the file is going to be completely useless in a few months.

**Comment by lhupfeldt** [comment]
Hi Werner,
Correct it is obsolete. I have deleted it.
Are you using multiconf?

**Comment by keilw** [comment]
Hi Lars, Thanks for the quick response.
Mostly for demo purposes right now. I got a "Triple-E DevOps" talk similar to the ones I held on different occasions on the Python day at DWX: https://www.developer-week.de/programm/#/talk/kokki-devops-toolchain-mit-python I saw Kokki was archived, do you use Multiconf with other DevOps build tools now? I guess I will mention Kokki but if Multiconf is now completely independent also alternatives, given it was archived and is therefore no longer actively developed.

**Comment by lhupfeldt** [comment]
Hi Werner,

Multiconf was never dependent on Kokki. Multiconf is a completely generic
multiple-env-specific-attibute-values library. It has been used as the
basis for a Domain Object Model used for the configuration of Weblogic,
JBoss, Apache, Linux and other technologies, but multiconf itself does not
provide the DOM, this must be implemented on top of multiconf as Python
classes. Kokki on the other hand was used to implement some of the recipes
acting on this DOM to perform the actual Linux configuration, Weblogic
domain creation, deployment, etc.

Multiconf could be used with some glue as the basis for Ansible
configuration providing the missing Ansible support for handling multiple
envs, while leveraging the nice Ansible ssh loop.

Regards / Venlig Hilsen
Lars Hupfeldt Nielsen
Hupfeldt IT

Phone: +45 2060 3546

2018-05-07 15:08 GMT+02:00 Werner Keil <notifications@github.com>:
